"""Code generation — export a PipelineConfig as a standalone Python module.

The generated file is self-contained: it imports from ``ravi``,
constructs all objects declared in the pipeline graph, and exposes an
``async def main()`` entry point that runs the pipeline.

Usage::

    from ravi.core.pipelines.codegen import generate_code
    from ravi.core.pipelines.schema import PipelineConfig

    config = PipelineConfig.model_validate(json_from_db)
    source_code: str = generate_code(config)

    with open("pipeline.py", "w") as f:
        f.write(source_code)
"""

from __future__ import annotations

import textwrap
from typing import List, Optional

from ravi.core.pipelines.schema import (
    EdgeType,
    NodeType,
    PipelineConfig,
)


def generate_code(config: PipelineConfig) -> str:
    """Generate a standalone Python module from a pipeline config."""
    sections: List[str] = []

    # ── Header ───────────────────────────────────────────────────────────
    sections.append(
        textwrap.dedent(f'''\
        """Auto-generated pipeline: {config.name}

        Generated by the Agent Framework Visual Builder.
        Run with:  uv run python {_safe_filename(config.name)}.py
        """

        from __future__ import annotations

        import asyncio
        import os

        from ravi.core.agent_catalog._catalog import AgentCatalog
        from ravi.core.agents.react_agent import ReActAgent
        from ravi.core.context.implementations import SlidingWindowContext
        from ravi.core.memory.unbounded_memory import UnboundedMemory
        from ravi.core.tools.base_tool import BaseTool, ToolResult
        from ravi.integrations.llm.openai.openai_client import OpenAIClient
    ''')
    )

    # Conditional imports based on node types
    node_types_used = {n.node_type for n in config.nodes}
    edge_types_used = {e.edge_type for e in config.edges}

    if NodeType.GUARDRAIL in node_types_used:
        sections.append(
            textwrap.dedent("""\
            from ravi.core.structured.judge import LLMJudge
            from ravi.core.structured.schemas import ContentSafetyJudge, RelevanceJudge
        """)
        )

    if NodeType.ROUTER in node_types_used:
        sections.append(
            textwrap.dedent("""\
            from ravi.core.structured.router import StructuredRouter
            from pydantic import BaseModel, Field, create_model
        """)
        )

    if EdgeType.AGENT_FLOW in edge_types_used:
        sections.append(
            textwrap.dedent("""\
            from ravi.core.agents.flow import ParallelFlow, SequentialFlow
        """)
        )

    if NodeType.CONDITION in node_types_used:
        sections.append(
            textwrap.dedent("""\
            from ravi.core.pipelines.condition_runner import ConditionPipelineRunner
        """)
        )

    if NodeType.SKILL in node_types_used:
        sections.append(
            textwrap.dedent("""\
            from ravi.catalog import SkillManager
        """)
        )

    if NodeType.MEMORY in node_types_used:
        _has_redis = any(
            n.config.get("backend") == "redis"
            for n in config.nodes_by_type(NodeType.MEMORY)
        )
        if _has_redis:
            sections.append(
                textwrap.dedent("""\
                from ravi.integrations.memory.redis_memory import RedisMemory
            """)
            )

    # Builtin tool imports — resolve which tool classes to import
    tool_names = set()
    for n in config.nodes_by_type(NodeType.TOOL):
        tool_names.add(n.config.get("tool_name", n.label))
    if tool_names:
        sections.append(_tool_imports(tool_names))

    # ── Setup section ────────────────────────────────────────────────────
    sections.append(
        textwrap.dedent("""\

        # ── Configuration ────────────────────────────────────────────────────

        OPENAI_API_KEY = os.environ.get("OPENAI_API_KEY", "")
        assert OPENAI_API_KEY, "Set OPENAI_API_KEY environment variable"

    """)
    )

    # ── Main function ────────────────────────────────────────────────────
    main_lines: List[str] = []
    main_lines.append("async def main() -> None:")
    main_lines.append(f'    """Run the {config.name} pipeline."""')
    main_lines.append("")

    # Build model clients
    agent_nodes = config.nodes_by_type(NodeType.AGENT)
    models_used = set()
    for an in agent_nodes:
        models_used.add(an.config.get("model", "gpt-4o-mini"))

    for model in sorted(models_used):
        var = _model_var(model)
        main_lines.append(
            f'    {var} = OpenAIClient(model="{model}", api_key=OPENAI_API_KEY)'
        )
    main_lines.append("")

    # Build tools
    for tool_name in sorted(tool_names):
        cls_name = _tool_class_name(tool_name)
        main_lines.append(f"    {tool_name}_tool = {cls_name}()")
    if tool_names:
        main_lines.append("")

    # Build memory instances
    for mem_node in config.nodes_by_type(NodeType.MEMORY):
        backend = mem_node.config.get("backend", "unbounded")
        var = f"memory_{_safe_var(mem_node.id[:8])}"
        if backend == "redis":
            ttl = mem_node.config.get("ttl", 3600)
            max_msgs = mem_node.config.get("max_messages", 200)
            main_lines.append(
                f'    {var} = RedisMemory(session_id="pipeline", default_ttl={ttl}, max_messages={max_msgs})'
            )
            main_lines.append(f"    await {var}.connect()")
        else:
            main_lines.append(f"    {var} = UnboundedMemory()")
    if config.nodes_by_type(NodeType.MEMORY):
        main_lines.append("")

    # Build skill managers
    for skill_node in config.nodes_by_type(NodeType.SKILL):
        pass  # Skills handled inline in agent construction

    # Build guardrails
    guardrail_vars = {}
    for gn in config.nodes_by_type(NodeType.GUARDRAIL):
        var = f"guard_{_safe_var(gn.id[:8])}"
        guardrail_vars[gn.id] = var
        schema = gn.config.get("schema", "ContentSafetyJudge")
        pass_field = gn.config.get("pass_field", "safe")
        sys_prompt = gn.config.get("system_prompt", f"Evaluate using {schema}.")
        tripwire = gn.config.get("tripwire_on_fail", False)
        # Use first model client
        client_var = _model_var(sorted(models_used)[0]) if models_used else "client"
        main_lines.append(f"    {var} = LLMJudge(")
        main_lines.append(f"        client={client_var},")
        main_lines.append(f"        schema={schema},")
        main_lines.append(f'        system_prompt="{_escape(sys_prompt)}",')
        main_lines.append(f'        pass_field="{pass_field}",')
        main_lines.append(f"        tripwire_on_fail={tripwire},")
        main_lines.append(f'        name="{gn.label or var}",')
        main_lines.append("    )")
    if guardrail_vars:
        main_lines.append("")

    # Build agents
    agent_vars = {}
    for an in agent_nodes:
        var = f"agent_{_safe_var(an.label or an.id[:8])}"
        agent_vars[an.id] = var
        model = an.config.get("model", "gpt-4o-mini")
        client_var = _model_var(model)

        # Find connected tools
        connected_tools = []
        for edge in config.edges_from(an.id):
            if edge.edge_type == EdgeType.AGENT_TOOL:
                tn = config.node_by_id(edge.target)
                if tn:
                    tname = tn.config.get("tool_name", tn.label)
                    connected_tools.append(f"{tname}_tool")

        # Find connected guardrails
        input_guards = []
        output_guards = []
        for edge in config.edges_from(an.id):
            if edge.edge_type == EdgeType.AGENT_GUARDRAIL:
                gn = config.node_by_id(edge.target)
                if gn and gn.id in guardrail_vars:
                    gtype = gn.config.get("guardrail_type", "output")
                    if gtype == "input":
                        input_guards.append(guardrail_vars[gn.id])
                    else:
                        output_guards.append(guardrail_vars[gn.id])

        # Find connected memory
        mem_var = "UnboundedMemory()"
        for edge in config.edges_from(an.id):
            if edge.edge_type == EdgeType.AGENT_MEMORY:
                mn = config.node_by_id(edge.target)
                if mn:
                    mem_var = f"memory_{_safe_var(mn.id[:8])}"

        sys_prompt = an.config.get("system_prompt", "You are a helpful assistant.")
        max_iter = an.config.get("max_iterations", 10)
        context_window = an.config.get("context_window", 40)

        catalog_var = f"catalog_{_safe_var(an.id[:8])}"
        main_lines.append(f"    {catalog_var} = AgentCatalog()")
        main_lines.append(f"    {catalog_var}.register_model('primary', {client_var})")
        main_lines.append(
            f"    {catalog_var}.register_context('default', SlidingWindowContext(max_messages={context_window}))"
        )
        main_lines.append(f"    {catalog_var}.register_memory('default', {mem_var})")
        for t in connected_tools:
            main_lines.append(f"    {catalog_var}.register_tool({t})")
        main_lines.append(f"    {var} = ReActAgent(")
        main_lines.append(f'        name="{_escape(an.label or "agent")}",')
        main_lines.append(
            f'        description="{_escape(an.config.get("description", ""))}",'
        )
        main_lines.append(f"        catalog={catalog_var},")
        main_lines.append(f'        system_instructions="""{sys_prompt}""",')
        main_lines.append(f"        max_iterations={max_iter},")
        main_lines.append("    )")
    main_lines.append("")

    # Build router if present
    router_nodes = config.nodes_by_type(NodeType.ROUTER)
    condition_nodes = config.nodes_by_type(NodeType.CONDITION)
    agent_flow_expr = _build_agent_flow_expression(config, agent_vars)
    if router_nodes:
        rn = router_nodes[0]
        rcfg = rn.config
        routing_key = rcfg.get("routing_key", "category")
        sys_prompt = rcfg.get("system_prompt", "Route the request.")

        # Build the routing schema
        fields = rcfg.get(
            "routing_fields",
            [
                {"name": "category", "type": "str", "description": "Routing category"},
                {"name": "reasoning", "type": "str", "description": "Explanation"},
            ],
        )
        main_lines.append("    # Dynamic routing schema")
        main_lines.append("    RoutingSchema = create_model(")
        main_lines.append('        "RoutingSchema",')
        for f in fields:
            ftype = f.get("type", "str")
            py_type = {
                "str": "str",
                "int": "int",
                "float": "float",
                "bool": "bool",
            }.get(ftype, "str")
            main_lines.append(
                f'        {f["name"]}=({py_type}, Field(description="{_escape(f.get("description", ""))}")),'
            )
        main_lines.append("    )")
        main_lines.append("")

        # Build routes dict
        route_edges = [
            e for e in config.edges_from(rn.id) if e.edge_type == EdgeType.ROUTER_ROUTE
        ]
        route_items = []
        for edge in route_edges:
            target = config.node_by_id(edge.target)
            if target and target.id in agent_vars:
                route_items.append(f'        "{edge.label}": {agent_vars[target.id]},')

        client_var = _model_var(sorted(models_used)[0]) if models_used else "client"
        main_lines.append("    router = StructuredRouter(")
        main_lines.append(f"        client={client_var},")
        main_lines.append("        routing_schema=RoutingSchema,")
        main_lines.append(f'        routing_key="{routing_key}",')
        main_lines.append("        routes={")
        main_lines.extend(route_items)
        main_lines.append("        },")
        main_lines.append(f'        system_prompt="""{sys_prompt}""",')
        main_lines.append("    )")
        main_lines.append("")
        main_lines.append(
            '    decision, result = await router.route([], input_text="What would you like?")'
        )
        main_lines.append("    print(f'Routed to: {decision.parsed}')")
        main_lines.append("    print(f'Result: {result}')")
    elif condition_nodes:
        # Build ConditionPipelineRunner for the first condition node
        cn = condition_nodes[0]
        ccfg = cn.config

        # Find upstream agent (CONDITION_INPUT edge coming into condition node)
        upstream_var = None
        for edge in config.edges_to(cn.id):
            if edge.edge_type == EdgeType.CONDITION_INPUT:
                src = config.node_by_id(edge.source)
                if src and src.id in agent_vars:
                    upstream_var = agent_vars[src.id]
                    break

        # Find branch agents (CONDITION_BRANCH edges going out)
        conditions_list = ccfg.get("conditions", [])
        branch_items: list[str] = []
        else_var = "None"
        for i, cond in enumerate(conditions_list):
            branch_id = f"cond-{i}"
            label = cond.get("label", f"branch_{i}")
            # Find a target node labeled with this branch
            for edge in config.edges_from(cn.id):
                if edge.edge_type == EdgeType.CONDITION_BRANCH and edge.label == label:
                    target = config.node_by_id(edge.target)
                    if target and target.id in agent_vars:
                        branch_items.append(
                            f'        "{branch_id}": {agent_vars[target.id]},'
                        )
                        break
        # else branch
        for edge in config.edges_from(cn.id):
            if edge.edge_type == EdgeType.CONDITION_BRANCH and edge.label in (
                "else",
                "default",
                "",
            ):
                target = config.node_by_id(edge.target)
                if target and target.id in agent_vars:
                    else_var = agent_vars[target.id]
                    break

        conditions_repr = repr(conditions_list)
        if upstream_var is None and agent_vars:
            upstream_var = list(agent_vars.values())[0]

        main_lines.append(
            "    # Condition pipeline — branches on expression evaluation"
        )
        main_lines.append("    condition_runner = ConditionPipelineRunner(")
        main_lines.append(f"        upstream_agent={upstream_var or 'None'},")
        main_lines.append(f"        conditions={conditions_repr},")
        main_lines.append("        branch_agents={")
        main_lines.extend(branch_items)
        main_lines.append("        },")
        main_lines.append(f"        else_agent={else_var},")
        main_lines.append("    )")
        main_lines.append("")
        main_lines.append(
            '    result = await condition_runner.run("Hello! How can I help?")'
        )
        main_lines.append("    print(result)")
    elif agent_flow_expr:
        main_lines.append("    workflow = " + agent_flow_expr)
        main_lines.append("")
        main_lines.append('    result = await workflow.run("Hello! What can you do?")')
        main_lines.append("    print(result.output)")
    elif agent_vars:
        first_var = list(agent_vars.values())[0]
        main_lines.append(
            f'    result = await {first_var}.run("Hello! What can you do?")'
        )
        main_lines.append("    print(result.output)")

    # ── Entry point ──────────────────────────────────────────────────────
    main_lines.append("")
    main_lines.append("")
    main_lines.append('if __name__ == "__main__":')
    main_lines.append("    asyncio.run(main())")
    main_lines.append("")

    sections.append("\n".join(main_lines))
    return "\n".join(sections)


# ── Utility functions ────────────────────────────────────────────────────────


def _safe_filename(name: str) -> str:
    return name.lower().replace(" ", "_").replace("-", "_")[:40]


def _safe_var(name: str) -> str:
    return name.lower().replace(" ", "_").replace("-", "_").replace(".", "_")


def _model_var(model: str) -> str:
    return f"client_{_safe_var(model)}"


def _escape(s: str) -> str:
    return s.replace('"', '\\"').replace("\n", "\\n")


def _build_agent_flow_expression(
    config: PipelineConfig,
    agent_vars: dict[str, str],
) -> Optional[str]:
    agent_ids = {node.id for node in config.nodes_by_type(NodeType.AGENT)}
    flow_edges = [
        edge
        for edge in config.edges
        if edge.edge_type == EdgeType.AGENT_FLOW
        and edge.source in agent_ids
        and edge.target in agent_ids
    ]
    if not flow_edges:
        return None

    incoming = {agent_id: [] for agent_id in agent_ids}
    outgoing = {agent_id: [] for agent_id in agent_ids}
    for edge in flow_edges:
        incoming[edge.target].append(edge.source)
        outgoing[edge.source].append(edge.target)

    ordered_agents = [node.id for node in config.nodes_by_type(NodeType.AGENT)]
    roots = [agent_id for agent_id in ordered_agents if not incoming[agent_id]]
    if len(roots) != 1:
        return None

    return _build_agent_flow_step_expression(
        roots[0],
        agent_vars=agent_vars,
        incoming=incoming,
        outgoing=outgoing,
    )


def _build_agent_flow_step_expression(
    agent_id: str,
    *,
    agent_vars: dict[str, str],
    incoming: dict[str, list[str]],
    outgoing: dict[str, list[str]],
    blocked_targets: Optional[set[str]] = None,
) -> str:
    blocked = blocked_targets or set()
    current_expr = agent_vars[agent_id]
    next_targets = [
        target_id
        for target_id in outgoing.get(agent_id, [])
        if target_id not in blocked
    ]
    if not next_targets:
        return current_expr

    if len(next_targets) == 1:
        next_id = next_targets[0]
        if len(incoming.get(next_id, [])) > 1:
            return current_expr

        next_expr = _build_agent_flow_step_expression(
            next_id,
            agent_vars=agent_vars,
            incoming=incoming,
            outgoing=outgoing,
            blocked_targets=blocked,
        )
        return (
            f"SequentialFlow(steps=[{current_expr}, {next_expr}], "
            f'name="{_safe_var(agent_id)}_sequence", '
            'description="Sequential multi-agent flow")'
        )

    join_id = _find_direct_join(
        branch_ids=next_targets, outgoing=outgoing, blocked_targets=blocked
    )
    branch_blocked = blocked | ({join_id} if join_id else set())
    branch_exprs = [
        _build_agent_flow_step_expression(
            branch_id,
            agent_vars=agent_vars,
            incoming=incoming,
            outgoing=outgoing,
            blocked_targets=branch_blocked,
        )
        for branch_id in next_targets
    ]
    parallel_expr = (
        f"ParallelFlow(branches=[{', '.join(branch_exprs)}], "
        f'name="{_safe_var(agent_id)}_parallel", '
        'description="Parallel specialist execution")'
    )
    steps = [current_expr, parallel_expr]
    if join_id:
        steps.append(
            _build_agent_flow_step_expression(
                join_id,
                agent_vars=agent_vars,
                incoming=incoming,
                outgoing=outgoing,
                blocked_targets=blocked,
            )
        )
    return (
        f"SequentialFlow(steps=[{', '.join(steps)}], "
        f'name="{_safe_var(agent_id)}_flow", '
        'description="Agent flow pipeline")'
    )


def _find_direct_join(
    *,
    branch_ids: list[str],
    outgoing: dict[str, list[str]],
    blocked_targets: set[str],
) -> Optional[str]:
    join_targets: list[str] = []
    for branch_id in branch_ids:
        candidates = [
            target_id
            for target_id in outgoing.get(branch_id, [])
            if target_id not in blocked_targets
        ]
        if len(candidates) != 1:
            return None
        join_targets.append(candidates[0])

    candidate = join_targets[0]
    if candidate in branch_ids:
        return None
    if all(target_id == candidate for target_id in join_targets[1:]):
        return candidate
    return None


_TOOL_CLASS_MAP = {
    "calculator": "CalculatorTool",
    "get_current_time": "GetCurrentTimeTool",
    "data_visualizer": "DataVisualizerTool",
    "markdown_previewer": "MarkdownPreviewerTool",
    "json_explorer": "JsonExplorerTool",
    "color_palette": "ColorPaletteTool",
    "kanban_board": "KanbanBoardTool",
    "spotify_player": "SpotifyPlayerTool",
}

_TOOL_IMPORT_MAP = {
    "calculator": "from ravi.core.tools.builtin_tools import CalculatorTool",
    "get_current_time": "from ravi.core.tools.builtin_tools import GetCurrentTimeTool",
    "data_visualizer": "from ravi.integrations.mcp.app_tools import DataVisualizerTool",
    "markdown_previewer": "from ravi.integrations.mcp.app_tools import MarkdownPreviewerTool",
    "json_explorer": "from ravi.integrations.mcp.app_tools import JsonExplorerTool",
    "color_palette": "from ravi.integrations.mcp.app_tools import ColorPaletteTool",
    "kanban_board": "from ravi.integrations.mcp.app_tools import KanbanBoardTool",
    "spotify_player": "from ravi.integrations.mcp.app_tools import SpotifyPlayerTool",
}


def _tool_class_name(tool_name: str) -> str:
    return _TOOL_CLASS_MAP.get(tool_name, f"Custom_{_safe_var(tool_name)}")


def _tool_imports(names: set) -> str:
    lines = []
    for name in sorted(names):
        imp = _TOOL_IMPORT_MAP.get(name)
        if imp:
            lines.append(imp)
    return "\n".join(lines) + "\n" if lines else ""
